21F1005173 Final Project/website/views.py
from flask import Blueprint, render_template, request, flash, redirect, url_for
from flask_login import login_required, current_user

views = Blueprint('views', __name__)


@views.route('/')
@login_required
def home():
    from .models import Tracker
    tracker = Tracker.query.all()
    return render_template("home.html", user=current_user, tracker=tracker)


@views.route('/view-profile', methods=['GET', 'POST'])
@login_required
def view_profile():
    return render_template("profile_page.html", user=current_user)


@views.route('/edit-profile-page', methods=['GET', 'POST'])
@login_required
def edit_profile_page():
    try:
        if request.method == 'POST':
            email = request.form.get('email')
            fullname = request.form.get('name')
            gender = request.form.get('gender')
            user_id = current_user.id
            current_user_email = current_user.email

            from .models import User
            user = User.query.filter_by(email=email).first()
            if user and current_user_email != email:
                flash('Email is already taken, try another email.', category='error')
            elif len(fullname) < 3:
                flash('Full name must be greater than 2 characters.', category='error')
            elif len(email) < 4:
                flash('Email must be greater than 3 characters.', category='error')
            else:
                from .models import User
                edit_user = User.query.get(user_id)

                from . import db

                edit_user.fullname = fullname
                edit_user.email = email
                edit_user.gender = gender

                db.session.commit()
                flash('Profile Updated Successfully.', category='success')
                return redirect(url_for('views.view_profile'))
    except Exception as e:
        print(e)
        flash('Something went wrong.', category='error')
    return render_template("edit_profile_page.html", user=current_user)


@views.route('/add-tracker-page', methods=['GET', 'POST'])
@login_required
def add_tracker_page():
    try:
        if request.method == 'POST':
            name = request.form.get('name')
            description = request.form.get('description')
            tracker_type = request.form.get('type')
            settings = request.form.get('settings')

            from .models import Tracker
            current_user_id = current_user.id
            tracker = Tracker.query.filter_by(name=name).first()
            if tracker and current_user_id == tracker.user_id:
                flash('The tracker "' + name + '" is already added by you.', category='error')
                return redirect(url_for('views.home'))
            else:
                from . import db
                new_tracker = Tracker(name=name, description=description, tracker_type=tracker_type, settings=settings,
                                      user_id=current_user_id)
                db.session.add(new_tracker)
                db.session.commit()
                flash('New Tracker Added.', category='success')
                return redirect(url_for('views.home'))
    except Exception as e:
        print(e)
        flash('Something went wrong.', category='error')
    return render_template("add_tracker_page.html", user=current_user)


@views.route('/delete-tracker/<int:record_id>', methods=['GET', 'POST'])
@login_required
def delete_tracker(record_id):
    try:
        from .models import Tracker
        Tracker_details = Tracker.query.get(record_id)
        Tracker_name = Tracker_details.name
        from . import db
        db.session.delete(Tracker_details)
        db.session.commit()
        flash(Tracker_name + ' Tracker Removed Successfully.', category='success')
    except Exception as e:
        print(e)
        flash('Something went wrong.', category='error')
    return redirect(url_for('views.home'))


@views.route('/edit-tracker/<int:record_id>', methods=['GET', 'POST'])
@login_required
def edit_tracker(record_id):
    from .models import Tracker
    this_tracker = Tracker.query.get(record_id)
    this_tracker_name = this_tracker.name
    try:
        if request.method == 'POST':
            name = request.form.get('name')
            description = request.form.get('description')
            tracker_type = request.form.get('type')
            settings = request.form.get('settings')

            current_user_id = current_user.id
            tracker = Tracker.query.filter_by(name=name).first()
            if tracker and tracker.user_id == current_user_id and this_tracker_name != name:
                flash('The tracker "' + name + '" is already added by you, Try a new name for your tracker.',
                      category='error')
            else:
                from . import db

                this_tracker.name = name
                this_tracker.description = description
                this_tracker.tracker_type = tracker_type
                this_tracker.settings = settings

                db.session.commit()
                flash('Tracker Updated Successfully.', category='success')
                return redirect(url_for('views.home'))
    except Exception as e:
        print(e)
        flash('Something went wrong.', category='error')

    return render_template("edit_tracker_page.html", user=current_user, tracker=this_tracker)


@views.route('/add-log-page/<int:record_id>', methods=['GET', 'POST'])
@login_required
def add_log(record_id):
    from .models import Tracker, Log
    this_tracker = Tracker.query.get(record_id)
    import datetime
    now = datetime.datetime.now()
    try:
        if request.method == 'POST':
            when = request.form.get('date')
            value = request.form.get('value')
            notes = request.form.get('notes')
            from . import db
            new_log = Log(timestamp=when, value=value, notes=notes, tracker_id=record_id, user_id=current_user.id,
                          added_date_time=now)
            db.session.add(new_log)
            db.session.commit()
            flash('New log added for ' + this_tracker.name + ' tracker', category='success')
            return redirect(url_for('views.home'))
    except Exception as e:
        print(e)
        flash('Something went wrong.', category='error')
    return render_template("add_log_page.html", user=current_user, tracker=this_tracker, now=now)


@views.route('/view-tracker-graph-logs/<int:record_id>', methods=['GET', 'POST'])
@login_required
def view_tracker(record_id):
    from .models import Tracker, Log
    import datetime
    now = datetime.datetime.now()
    selected_tracker = Tracker.query.get(record_id)
    logs = Log.query.all()
    try:
        import sqlite3
        con = sqlite3.connect('website\database.db')
        print("Database opened successfully")
        c = con.cursor()
        c.execute('SELECT timestamp, value FROM Log WHERE user_id={} AND tracker_id={}'.format(current_user.id,
                                                                                               selected_tracker.id))
        data = c.fetchall()

        dates = []
        values = []
        import matplotlib.pyplot as plt
        from matplotlib import style
        style.use('ggplot')
        from dateutil import parser

        for row in data:
            dates.append(parser.parse(row[0]))
            values.append(row[1])

        fig = plt.figure(figsize=(18, 8))
        plt.plot_date(dates, values,linestyle = 'dotted')
        plt.xlabel('Date and Time')
        plt.ylabel('Values')
        plt.tight_layout()
        plt.savefig('website\static\Images\graph.png')

        gon = sqlite3.connect('website\database.db')
        g = gon.cursor()
        added_date_time = g.execute('SELECT added_date_time FROM Log WHERE '
                                    'id=(SELECT max(id) FROM Log WHERE tracker_id={})'.format(record_id))

        added_date_time = added_date_time.fetchone()
        added_date_time = ''.join(added_date_time)
        print(added_date_time)
        from datetime import datetime
        last_updated = now - parser.parse(added_date_time)
        last_updated_str = str(last_updated)
        hour = last_updated_str[:1]
        min1 = last_updated_str[2]
        min2 = last_updated_str[3]
        minute = min1 + min2
        sec1 = last_updated_str[5]
        sec2 = last_updated_str[6]
        second = sec1 + sec2
        return render_template("view_tracker_logs_and_graph.html", user=current_user, tracker=selected_tracker,
                               logs=logs, hour=hour, min=minute, sec=second)
    except Exception as e:
        print(e)
        flash('Something went wrong.', category='error')
        return render_template("view_tracker_logs_and_graph.html", user=current_user, tracker=selected_tracker,
                               logs=logs)


@views.route('/delete-log/<int:record_id>', methods=['GET', 'POST'])
@login_required
def delete_log(record_id):
    from .models import Log
    Log_details = Log.query.get(record_id)
    tracker_id = Log_details.tracker_id
    try:
        from . import db
        db.session.delete(Log_details)
        db.session.commit()
        flash('Log Removed Successfully.', category='success')
    except Exception as e:
        print(e)
        flash('Something went wrong.', category='error')
    return redirect(url_for('views.view_tracker', record_id=tracker_id))


@views.route('/edit-log/<int:record_id>', methods=['GET', 'POST'])
@login_required
def edit_log(record_id):
    from .models import Log, Tracker
    from . import db
    this_log = Log.query.get(record_id)
    this_tracker = Tracker.query.get(this_log.tracker_id)
    try:
        if request.method == 'POST':
            when = request.form.get('date')
            value = request.form.get('value')
            notes = request.form.get('notes')

            this_log.timestamp = when
            this_log.value = value

21F1005173 Final Project/website/templates/add_log_page.html
{% extends 'base.html' %}
{% block title %}Add Log{% endblock %}
{% block content %}
<form method="post">
    <div class="form-group emp-profile container shadow-sm col-md-4" style="text-align:center;">
        <h5 style="padding-bottom: 5%;">Add log to {{tracker.name}}</h5>
        <div class="row" style="padding-bottom: 1.5%;">
            <div class="input-group">
                <span class="input-group-text">When:</span>
                <input type="datetime-local" class="form-control" id="date" name="date" style="text-align: center" value="{{now}}" required />
            </div>
        </div>    
        <div class="row" style="padding-bottom: 1.5%;">
            <div>
                {% if tracker.tracker_type=='Numerical' %}
                <input type="number" class="form-control" id="value" name="value" placeholder="Enter value" maxlength="30" style="text-align: center" required />
                {% elif tracker.tracker_type=='Fahrenheit' %}
                <input type="number" class="form-control" id="value" name="value" placeholder="Enter Fahrenheit" maxlength="30" style="text-align: center" required />
                {% elif tracker.tracker_type=='Mood' %}
                <select style="text-align: center;" id="value" class="form-control" name="value" required>
                    <option value="" disabled selected>Choose your mood</option>
                    <option value="Happy">Happy</option>
                    <option value="Sad">Sad</option>
                    <option value="Angry">Angry</option>
                    <option value="Depressed">Depressed</option>
                    <option value="Anxious">Anxious</option>
                </select>
                {% elif tracker.tracker_type=='Boolean' %}
                <input  type="radio" id="value" name="value" value="True" checked>
                <label  for="value">True</label>                
                <input  type="radio" id="value" name="value" value="False">
                <label  for="value">False</label>
                {% endif %}
            </div>
        </div>
        <div class="row" style="padding-bottom: 1.5%;">
            <div class="input-group">            
                <textarea class="form-control" id="notes" name="notes" placeholder="Enter log notes" maxlength="200" style="text-align: center" required></textarea>
            </div>    
        </div>    
        <br>
        <button type="submit" class="btn btn-light"><b>Add Log</b></button>
    </div>
</form>
{% endblock %}

21F1005173 Final Project/website/templates/add_tracker_page.html
{% extends 'base.html' %}
{% block title %}Add Tracker{% endblock %}
{% block content %}
<form method="post">
    <div class="form-group emp-profile container shadow-sm col-md-4" style="text-align: center;">
        <h5 style="padding-bottom: 5%;">Add Tracker</h5>
        <div class="row" style="padding-bottom: 1.5%;">
            <div class="input-group">
                <input type="text" class="form-control" id="name" name="name" placeholder="Enter tracker name" maxlength="30" style="text-align: center" required />
            </div>
        </div>
        <div class="row" style="padding-bottom: 1.5%;">
            <div class="input-group">
                <textarea class="form-control" id="description" name="description" placeholder="Enter tracker description" maxlength="200" style="text-align: center" required></textarea>
            </div>
        </div>    
        <div class="row" style="padding-bottom: 1.5%;">
            <div class="input-group">
                <select style="text-align: center" id="type" class="form-control" name="type" required>
                    <option value="" disabled selected>Select tracker type</option>
                    <option value="Numerical">Numerical</option>
                    <option value="Mood">Mood</option>
                    <option value="Fahrenheit">Fahrenheit</option>
                    <option value="Boolean">Boolean</option>
                </select>
            </div>
        </div>
        <div class="row" style="padding-bottom: 1.5%;">
            <div class="input-group">        
                <input type="text" class="form-control" id="settings" name="settings" placeholder="Enter tracker settings" maxlength="80" style="text-align: center" />
            </div>
        </div>    
        <br>
        <button type="submit" class="btn btn-light">Add Tracker</button>
    </div>
</form>

{% endblock %}

21F1005173 Final Project/website/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <!-- <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
    crossorigin="anonymous" />
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
  <link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
  <script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script> -->
  <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet">
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
  <link rel="stylesheet" type="text/css" href="../static/index.css" />
  <title>{% block title %}Home{% endblock %}</title>
</head>

<body class="d-flex flex-column min-vh-100">
  <div class="p-4 bg-secondary text-dark text-left"
    style="background-image:url('https://wallpaperaccess.com/full/12680.jpg');">
    <h1 style="text-shadow: #333333"><i><b>HabitTracker</b></i></h1>
    <p><b>Custom habit tracking tool</b></p>
  </div>
  <nav class="navbar navbar-expand-lg navbar-light bg-light" style="padding-left: 1.5%;">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbar">
      <div class="navbar-nav">
        {% if user.is_authenticated %}
        <a class="nav-item nav-link" id="home" href="/">Home</a>
        <a class="nav-item nav-link" id="profile" href="/view-profile">{{user.fullname}}</a>
        <a class="nav-item nav-link" id="logout" href="/logout">Logout</a>
        {% else %}
        <a class="nav-item nav-link" id="login" href="/login">Login</a>
        <a class="nav-item nav-link" id="signUp" href="/sign-up">Sign Up</a>
        {% endif %}
      </div>
    </div>
  </nav>
  {% with messages = get_flashed_messages(with_categories=true) %}
  {% if messages %}

  {% for category, message in messages %}

  {% if category == 'error' %}
  <div align="center">
    <div class="alert alert-danger alter-dismissable fade show" role="alert">
      {{ message }}
      <button type="button" class="close bg-transparent" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
  </div>
  {% else %}
  <div align="center">
    <div class="alert alert-success alter-dismissable fade show" role="alert">
      {{ message }}
      <button type="button" class="close bg-transparent" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
  </div>
  {% endif %}
  {% endfor %}
  {% endif %}
  {% endwith %}
  {% block content %}
  {% endblock %}
  <br>
  <footer class="mt-auto">  
    <div class="mt-5 p-2 bg-dark text-light text-left">
      <h5 style="padding-top: 0.5em;">HabitTracker</h5>
      <p class="text-secondary">© 2022</p>
    </div>
  </footer>   
  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
    integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
    crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
    integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
    crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
    integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
    crossorigin="anonymous"></script>
  <script type="text/javascript" src="{{ url_for('static', filename='index.js') }}"></script>
</body>
</html>

21F1005173 Final Project/website/templates/edit_log_page.html
{% extends 'base.html' %}
{% block title %}Edit Log{% endblock %}

{% block content %}
<form method="post">
    <div class="form-group emp-profile container shadow-sm col-md-4" style="text-align: center;">
        <h5 style="padding-bottom: 5%;">Edit Log</h5>
        <div class="row" style="padding-bottom: 1.5%;">
            <div class="input-group">
                <span class="input-group-text">When:</span>
                <input type="datetime-local" class="form-control" id="date" name="date" style="text-align: center" value="{{log.timestamp}}" />
            </div>
        </div>
        <div class="row" style="padding-bottom: 1.5%;">
            <div>
                {% if tracker.tracker_type=='Numerical' %}
                <input type="number" class="form-control" id="value" name="value" placeholder="Enter Number" maxlength="30" style="text-align: center" value="{{log.value}}" />
                {% elif tracker.tracker_type=='Fahrenheit' %}
                <input type="number" class="form-control" id="value" name="value" placeholder="Enter Fahrenheit" maxlength="30" style="text-align: center" value="{{log.value}}" />
                {% elif tracker.tracker_type=='Mood' %}
                <select style="text-align: center" id="value" class="form-control" name="value" required>
                    <option value="{{log.value}}">{{log.value}}</option>
                    <option value="Happy">Happy</option>
                    <option value="Sad">Sad</option>
                    <option value="Angry">Angry</option>
                    <option value="Depressed">Depressed</option>
                    <option value="Anxious">Anxious</option>
                </select>
                {% elif tracker.tracker_type=='Boolean' %}
                {% if log.value=='True' %}
                <input type="radio" id="value" name="value" value="{{log.value}}" checked>
                <label for="value">{{log.value}}</label>
                <input type="radio" id="value" name="value" value="False">
                <label for="value">False</label>
                {% else %}
                <input type="radio" id="value" name="value" value="True">
                <label for="value">True</label><br>
                <input type="radio" id="value" name="value" value="{{log.value}}" checked>
                <label for="value">{{log.value}}</label><br>
                {% endif %}

                {% endif %}
            </div>
        </div>
        <div class="row" style="padding-bottom: 1.5%;">
            <div class="input-group">            
                <textarea class="form-control" id="notes" name="notes" placeholder="Enter log notes" maxlength="200" style="text-align: center">{{log.notes}}</textarea>
            </div>
        </div>        
        <br>
        <button type="submit" class="btn btn-light"><b>Update Log</b></button>
    </div>
</form>
{% endblock %}

21F1005173 Final Project/website/templates/edit_profile_page.html
{% extends 'base.html' %}
{% block title %}Edit Profile{% endblock %}

{% block content %}

<form method="post">
    <div class="form-group emp-profile container shadow-sm col-md-4" style="text-align:center;">
        <h5 style="padding-bottom: 5%;">Edit Profile</h5>
        <div class="row" style="padding-bottom: 1.5%;">
            <div class="input-group">
                <input type="text" class="form-control" id="name" name="name" placeholder="Enter your full name" maxlength="30"  style="text-align: center" value="{{ user.fullname }}" />
            </div>
        </div>            
        <div class="row" style="padding-bottom: 1.5%;">
            <div class="input-group">
                <input type="email" class="form-control" id="email" name="email" placeholder="Enter your email address" maxlength="35" style="text-align: center" value="{{ user.email }}" />
            </div>
        </div>
        <div class="row" style="padding-bottom: 1.5%;">
            <div class="input-group">    
                <select style="text-align: center" id="gender"  class="form-control"  name="gender" required>
                    <option value="{{ user.gender }}">{{ user.gender }}</option>
                    <option value="Male">Male</option>
                    <option value="Female">Female</option>
                    <option value="Prefer not to disclose">Prefer not to disclose</option>
                </select>
            </div>
        </div>
        <br>
        <button type="submit" class="btn btn-light" >Update Profile</button>
    </div>
</form>
{% endblock %}

21F1005173 Final Project/website/templates/edit_tracker_page.html
{% extends 'base.html' %}
{% block title %}Edit Tracker{% endblock %}

{% block content %}
<form method="post">
    <div class="form-group emp-profile container shadow-sm col-md-4" style="text-align: center;">
        <h5 style="padding-bottom: 5%;">Edit Tracker</h5>
        <div class="row" style="padding-bottom: 1.5%;">
            <div class="input-group">
                <input type="text" class="form-control" id="name" name="name" placeholder="Enter tracker name" maxlength="30" style="text-align: center" value="{{ tracker.name }}" />
            </div>
        </div>
        <div class="row" style="padding-bottom: 1.5%;">
            <div class="input-group">     
                <textarea class="form-control" id="description" name="description" placeholder="Enter tracker description" maxlength="200" style="text-align: center">{{ tracker.description }}</textarea>
            </div>
        </div>    
        <div class="row" style="padding-bottom: 1.5%;">
            <div class="input-group">
                <select style="text-align: center" id="type" class="form-control" name="type" required>
                    <option value="{{ tracker.tracker_type }}">{{ tracker.tracker_type }}</option>
                    <option value="Numerical">Numerical</option>
                    <option value="Multiple Choice">Multiple Choice</option>
                    <option value="Fahrenheit">Fahrenheit</option>
                    <option value="Boolean">Boolean</option>
                </select>
            </div>
        </div>            
        <div class="row" style="padding-bottom: 1.5%;">
            <div class="input-group">
                <input type="text" class="form-control" id="settings" name="settings" placeholder="Enter tracker settings" maxlength="80" style="text-align: center" value="{{ tracker.settings }}" />
            </div>
        </div>        
        <br>
        <button type="submit" class="btn btn-light"><b>Update Tracker</b></button>
    </div>
</form>

{% endblock %}

21F1005173 Final Project/website/templates/home.html
{% extends 'base.html' %}
{% block title %}Dashboard{% endblock %}
{% block content %}

<br>
<div class="container emp-profile shadow-sm col-md-6">
  <table class="table table-hover align-middle">
    <thead class="table">
      <tr>
        <th scope="col">Tracker</th>
        <th scope="col">Description</th>
        <th scope="col"></th>
        <th scope="col"></th>
      </tr>
    </thead>
    <tbody>
      {% for tracker in tracker %}
      {% if tracker.user_id==user.id %}
      <tr>
        {% set tracker_id=tracker.id %}
        <td><a href="{{ url_for('views.view_tracker', record_id = tracker_id) }}" style="text-decoration: none;">{{tracker.name}}</a></td>
        <td>{{tracker.description}}</td>
        <td><a href="{{ url_for('views.add_log', record_id = tracker_id) }}" class="btn btn-light" style="font-weight: 100 ;">✚</a></td>
        <td>
          <div class="dropdown">
            <button class="btn btn-light dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Actions</button>
            <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
              <a class="dropdown-item" href="{{ url_for('views.edit_tracker', record_id = tracker_id) }}">Edit Tracker</a>
              <a class="dropdown-item" href="{{ url_for('views.delete_tracker', record_id = tracker_id) }}">Remove Tracker</a>
            </div>
          </div>
        </td>
      </tr>
      {% endif %}
      {% endfor %}
    </tbody>
  </table>
  <div align="center">
    <a href="/add-tracker-page" class="btn btn-light">Add Tracker</a>
  </div>
</div>
{% endblock %}

21F1005173 Final Project/website/templates/login.html
{% extends 'base.html' %}
{% block title %}Login{% endblock %}
{% block content %}
<form method="post">
    <div class="form-group emp-profile container shadow-sm col-md-4" style="text-align: center;">
        <h5 style="padding-bottom: 5%;">Login to Habit Tracker</h5>
        <div class="row" style="padding-bottom: 1.5%;">
            <div class="input-group">
                <input type="email" class="form-control" id="email" name="email" placeholder="Enter your email address" style="text-align: center;" required/>
            </div>
        </div>   
        <div class="row" style="padding-bottom: 1.5%;">
            <div class="input-group">
                <input type="password" class="form-control" id="password" name="password" placeholder="Enter your password" style="text-align: center;" required/>
            </div>
        </div>
        <br>
        <button class="btn btn-light">Login</button>
    </div>
</form>
{% endblock %}

21F1005173 Final Project/website/templates/view_tracker_logs_and_graph.html
{% extends 'base.html' %}
{% block title %}View Tracker Logs{% endblock %}
{% block content %}
<div class="container shadow-sm emp-profile profile-head">
  <form method="post">
    <div>
      <h3>{{ tracker.name }} tracker</h3>
      <h4><small style="font-size: 12px">last updated : {{hour}} hours {{min}} minutes {{sec}} seconds ago</small></h4>
    </div>
    <ul class="nav nav-tabs">
      <li class="nav-item"><a class="nav-link active" data-toggle="tab" href="#graph">Graph</a></li>
      <li class="nav-item"><a class="nav-link" data-toggle="tab" href="#logs">Logs</a></li>
    </ul>
    <div class="tab-content">
      <div id="graph" class="tab-pane fade show active">
        <img src="{{url_for('static',filename='Images/graph.png')}}" alt="" style="width: 900px;height: 350px">
      </div>
      <div id="logs" class="tab-pane fade">
        <table class="table table-hover align-middle">
          <thead class="thead-dark">
            <tr>
              <th scope="col">On</th>
              <th scope="col">Value</th>
              <th scope="col">Notes</th>
              <th scope="col"></th>
            </tr>
          </thead>
          <tbody>
            {% for log in logs %}
            {% if log.user_id==user.id and log.tracker_id==tracker.id %}
            <tr>
              {% set log_id=log.id %}
              <td>{{log.timestamp}}</td>
              <td>{{log.value}}</td>
              <td>{{log.notes}}</td>
              <td>
                <div class="dropdown">
                  <button class="btn btn-light dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Actions</button>
                  <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                    <a class="dropdown-item" href="{{ url_for('views.edit_log', record_id = log_id) }}">Edit Log</a>
                    <a class="dropdown-item" href="{{ url_for('views.delete_log', record_id = log_id) }}">Remove Log</a>
                  </div>
                </div>       
              </td>
            </tr>
            {% endif %}
            {% endfor %}        
          </tbody>
        </table>
      </div>
    </div>
  </form>
</div>
{% endblock %}